#Here, you can edit the various settings for the BasicImprovements plugin.

#~----------------
#Event Messages
#You can utilize "&" to create colors and <player> will substitute the name of the player.

#The message displayed when a player first joins the server.
firstjoin_message: "<player> &dhas joined the server for the first time!"

#The message displayed when a player rejoins the server.
join_message: "<player> &fhas joined the server"

#The message displayed when a player leaves the server.
leave_message: "<player> &fhas left the server"

#The message displayed when a player is kicked.
kick_message: "<player> &fhas been kicked (<reason>)"

#The message displayed when a player sleeps.
sleep_message: "<player> &aslept in a bed"

#The message displayed when a player has been fed.
feed_receive_message: "&aYou have been fed by <player>"

#The message displayed when a player feeds another player.
feed_give_message: "&aSuccessfully fed <player>"

#The message displayed then a player heals another player.
heal_receive_message: "&aYou have been healed by <player>"

#The message displayed when a player has been healed.
heal_give_message: "&aSuccessfully healed <player>"

#The message displayed when a player updates another player's gamemode.
gamemode_give_update: "&fSuccessfully updated gamemode for <player>"
    
#The message displayed when a player's gamemode is updated.
gamemode_receive_update: "&fYour gamemode has been updated by <player>"

#The message displayed when a backup starts.
backup_started: "&fBackup started..."

#The message displayed when a backup finishes.
backup_finished: "&fBackup completed successfully"

#The message displayed when a player changes the time to day.
time_set_day: "<player> &fSet the time to &eday"

#The message displayed when a player changes the time to night.
time_set_night: "<player> &fSet the time to &enight"
    
#~----------------
#Backup Settings

#The path that the backups are created in.
backup_path: plugins/BasicImprovements/backups

#The total number of backups to keep.
kept_versions: 10

#The time to make the backups at, as of now the interval is once per day.
#Only the hour is editable and it is based on a 24hr clock:
#1: 1:00am          13: 1:00pm
#2: 2:00am          14: 2:00pm
#3: 3:00am          15: 3:00pm
#4: 4:00am          16: 4:00pm
#5: 5:00am          17: 5:00pm
#6: 6:00am          18: 6:00pm
#7: 7:00am          19: 7:00pm
#8: 8:00am          20: 8:00pm
#9: 9:00am          21: 9:00pm
#10: 10:00am        22: 10:00pm
#11: 11:00am        23: 11:00pm
#12: 12:00pm        24: 12:00am
backup_time: 24

#~----------------
#Miscellaneous Settings

#Choose whether to hide the command issuer or not.
obfuscate_command_issuer: false